# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_datetime',
            field=models.DateTimeField(),
        ),
    ]
